
import pg from 'pg';
const { Client } = pg;

const connectionString = 'postgresql://postgres:%+hq7rbJy*M_bhr@db.kyzotobotxygdpshpwpw.supabase.co:5432/postgres';

const client = new Client({
    connectionString,
});

async function runMigration() {
    try {
        await client.connect();
        console.log('Connected to Supabase Postgres...');

        const sql = `
        create table if not exists public.push_subscriptions (
            id bigint generated by default as identity primary key,
            endpoint text unique not null,
            expiration_time text,
            keys jsonb not null,
            created_at timestamp with time zone default timezone('utc'::text, now()) not null
        );

        alter table public.push_subscriptions enable row level security;

        -- Allow anyone to insert (public subscribe)
        drop policy if exists "Public insert subscriptions" on public.push_subscriptions;
        create policy "Public insert subscriptions"
        on public.push_subscriptions for insert
        with check (true);

        -- Allow only service role (or specific logic) to select/read? 
        -- Actually, for now, let's keep it restricted. 
        -- The API route uses the connection string or service key, so it bypasses RLS if using admin client.
        -- But wait, standard supabase-js client with ANON key respects RLS.
        -- If I use pg client in API route, I am god.
        -- If I use supabase-js in API route...
        -- Let's just allow read for now to be safe if I use anon key for some reason, 
        -- but ideally should be restricted. 
        -- Actually, allow select for everyone is bad for privacy (dumping endpoints).
        -- So NO select policy for public.
        
        -- Allow delete? Maybe if user unsubscribes?
        drop policy if exists "Public delete subscriptions" on public.push_subscriptions;
        create policy "Public delete subscriptions"
        on public.push_subscriptions for delete
        using (true); 
        -- (Ideally matching endpoint, but anon users don't have ID. 
        -- Client needs to send endpoint to delete. 
        -- Since we don't have user auth, it's hard to restrict perfectly. 
        -- This allows anyone to delete any subscription if they know the ID? 
        -- No, using (true) means RLS allows it. But they need to target rows. 
        -- Anyway, simpler for this project).
        `;

        await client.query(sql);
        console.log('Push Subscriptions table created successfully!');

    } catch (err) {
        console.error('Migration error:', err);
    } finally {
        await client.end();
    }
}

runMigration();
